import { PokemonCard } from "@poc/components/organisms/PokemonCard";
import Head from "next/head";

const types = [
  {
    slot: 1,
    type: {
      name: "grass",
      url: "https://pokeapi.co/api/v2/type/12/",
    },
  },
];
const status = [
  {
    base_stat: 45,
    effort: 0,
    stat: {
      name: "hp",
      url: "https://pokeapi.co/api/v2/stat/1/",
    },
  },
  {
    base_stat: 49,
    effort: 0,
    stat: {
      name: "attack",
      url: "https://pokeapi.co/api/v2/stat/2/",
    },
  },
  {
    base_stat: 65,
    effort: 0,
    stat: {
      name: "defense",
      url: "https://pokeapi.co/api/v2/stat/3/",
    },
  },
  {
    base_stat: 49,
    effort: 0,
    stat: {
      name: "special-attack",
      url: "https://pokeapi.co/api/v2/stat/4/",
    },
  },
  {
    base_stat: 65,
    effort: 1,
    stat: {
      name: "special-defense",
      url: "https://pokeapi.co/api/v2/stat/5/",
    },
  },
  {
    base_stat: 45,
    effort: 0,
    stat: {
      name: "speed",
      url: "https://pokeapi.co/api/v2/stat/6/",
    },
  },
];
const name = "chikorita";
const url =
  "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/152.png";
export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex - Next with strapi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full p-4 flex justify-center">
        <PokemonCard name={name} image={url} types={types} status={status} />
      </main>
    </>
  );
}
